name: Create PR for Environment Promotion

on:
  # Runs on pushes targeting the default branch
  push:
    paths-ignore:
      - "LICENSE"
      - "README.md"
    branches:
      - staging
      - develop

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write

jobs:
  create-pr:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Create PR to Promote 'develop' to 'staging'
        if: github.ref == 'refs/heads/develop'
        run: |
          gh pr create \
            --title "Promote Develop to Staging" \
            --body "This PR is automatically created and left open until ready to be merged" \
            --base staging

      - name: Create PR to Promote 'staging' to 'production'
        if: github.ref == 'refs/heads/staging'
        run: |
          gh pr create \
            --title "Promote Staging to Production" \
            --body "This PR is automatically created and left open until ready to be merged" \
            --base main
